name: 'MC-DepUp'
description: "Let's dep-up your mods! It automatically updates Minecraft version and dependencies in your gradle.properties"
author: 'LucunJi'

branding:
  icon: 'chevrons-up'
  color: 'yellow'

inputs:
  config_path:
    description: |
      'Path to the config file'
    default: './.github/modding-dependencies.yml'

  update_mc_patch:
    description: |
      'Update patch version of Minecraft'
      'true | false'
    default: true

  update_only_with_mc:
    description: |
      'Update only when Minecraft updates (depends on update_mc_patch)'
      'true | false'
    default: false

  tolerable:
    description: |
      'Allow the update of any dependency to fail'
      'true | false'
    default: false

  dry_run:
    description: |
      'The new configuration is not written to the file'
      'true | false'
    default: false

outputs:
  any_update:
    description: |
      'Anything new according to configured update'
      'true | false'

runs:
  using: node20
  main: dist/index.js
