name: 'MC-DepUp'
description: "Let's dep-up your mods! It automatically update the dependencies whenever a new minecraft version is released"
author: 'LucunJi'

branding:
  icon: 'chevrons-up'
  color: 'yellow'

inputs:
  update_mc_patch:
    description: |
      'Update patch version of Minecraft'
      'true | false'
    default: true

  update_only_with_mc:
    description: |
      'Update only when Minecraft updates (depends on update_mc_patch)'
      'true | false'
    default: false

  tolerable:
    description: |
      'Allow any of the configured dependency to fail'
      'true | false'
    default: false

outputs:
  any_update:
    description: |
      'Anything new according to configured update'
      'true | false'

runs:
  using: node21
  main: dist/index.js
