name: 'Minecraft Modding Updater'
description: 'Automatically update the dependencies whenever a new minecraft version is released'
author: 'LucunJi'

branding:
  icon: 'chevrons-up'
  color: 'yellow'

# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node21
  main: dist/index.js
